version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: smarttrip-postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - smarttrip-net

  backend:
    build:
      context: ./backend/smarttrip
    container_name: smarttrip-backend
    depends_on:
      - postgres
      - flask-ml
    env_file:
      - .env
    ports:
      - "18080:8080"
    networks:
      - smarttrip-net

  flask-ml:
    build:
      context: ./backend/flask-model-api
    container_name: smarttrip-ml
    volumes:
      - /home/student/ml-cache:/app/cache
    networks:
      - smarttrip-net

volumes:
  postgres-data:

networks:
  smarttrip-net:
