version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: smarttrip-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: smart-trip
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - smarttrip-net

  backend:
    build:
      context: ../backend/smarttrip
    container_name: smarttrip-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - flask-ml
    environment:
      # SPRING_SERVER_ADDRESS: 0.0.0.0
      SPRING_APPLICATION_JSON: '{ "server.address": "0.0.0.0" }'
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/smart-trip
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      ML_SERVICE_URL: http://flask-ml:5000
    networks:
      - smarttrip-net

  flask-ml:
    build:
      context: ../backend/flask-model-api
    container_name: smarttrip-ml
    ports:
      - "5000:5000"
    networks:
      - smarttrip-net

volumes:
  postgres-data:

networks:
  smarttrip-net:
