version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: smarttrip-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: smart-trip
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - smarttrip-net

  backend:
    build:
      context: ../backend/smarttrip
    container_name: smarttrip-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - flask-ml
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/smart-trip
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      ML_SERVICE_URL: http://flask-ml:5000
    networks:
      - smarttrip-net

  frontend:
    build:
      context: ../frontend/apps/web
    container_name: smarttrip-frontend
    networks:
      - smarttrip-net

  flask-ml:
    build:
      context: ../backend/flask-model-api
    container_name: smarttrip-ml
    ports:
      - "5000:5000"
    networks:
      - smarttrip-net

  nginx:
    image: nginx:alpine
    container_name: smarttrip-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/apps/web/dist:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend
      - flask-ml
    networks:
      - smarttrip-net

volumes:
  postgres-data:

networks:
  smarttrip-net:
