name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build-and-dockerize:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout code
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # 3. Build Docker images using docker-compose
    - name: Build and start services with Docker Compose
      run: |
        cd docker
        docker-compose -f docker-compose.yml build
        docker-compose -f docker-compose.yml up -d

    # 4. Optionally, Push Docker images to DockerHub (if desired)
    # - name: Push Docker images to DockerHub
    #   if: github.event_name == 'push'
    #   run: |
    #     echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    #     docker-compose -f docker/docker-compose.yml push
