name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install frontend dependencies
        run: npm install
        working-directory: frontend/apps/web

      - name: Build frontend
        run: npm run build
        working-directory: frontend/apps/web

      - name: Upload frontend to server (temporary dir)
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./frontend/apps/web/dist/**"
          target: "/home/student/smarttrip-temp"

      - name: Deploy frontend via SSH (move & permission)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo mkdir -p /var/www/smarttrip
            sudo chown -R student:student /var/www/smarttrip
            sudo rm -rf /var/www/smarttrip/*
            sudo mv /home/student/smarttrip-temp/* /var/www/smarttrip/
            sudo chown -R www-data:www-data /var/www/smarttrip
            rm -rf /home/student/smarttrip-temp

      - name: Deploy backend via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/student/COMP47360
            docker-compose down
            docker-compose up -d --build
